# Generated by Django 2.1.5 on 2020-02-01 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=36)),
                ('model_spec', models.CharField(max_length=36)),
                ('ICON_ref', models.CharField(max_length=36)),
                ('availability', models.BooleanField(default=True)),
                ('borrow_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('asset_number', models.CharField(blank=True, max_length=32, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=32, null=True)),
                ('location', models.CharField(blank=True, default='storeroom', max_length=120, null=True)),
                ('value', models.CharField(blank=True, max_length=10, null=True)),
                ('PAT', models.DateField(blank=True, null=True)),
                ('current_user', models.EmailField(blank=True, default='', max_length=72, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('db_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
